version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - copyloopvar
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - intrange
    - ireturn
    - lll
    - mnd
    - nolintlint
    - nonamedreturns
    - paralleltest
    - staticcheck
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - err113
          - funlen
          - goconst
          - mnd
          - noctx
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
